Style and implementation of component avatar
nelfan/BORDA-React-UI pull request #8
Opened 2021-05-31 05:40 UTC by jules-n

Small component, that implements the functionality of user's image and "mini avatar"

2021-05-31 06:31 UTC, ChernykhVyacheslav approved these changes

2021-05-31 08:30 UTC, achehrynets requested changes
Looks good, except for few code style issues.

2021-05-31 08:30 UTC, achehrynets commented on src/components/ProfilePage/Avatar/Avatar.js
> +        <img className="img"  ref = {ref}onClick={props.onClick} src={props.src} width={props.width} alt="user's avatar" accept=".jpg, .jpeg, .png"></img>
Fix code style (formatting):
`ref = {ref}onClick={props.onClick}`

2021-05-31 08:30 UTC, achehrynets commented on src/components/ProfilePage/Avatar/Avatar.js
> +        <img className="img"  ref = {ref}onClick={props.onClick} src={props.src} width={props.width} alt="user's avatar" accept=".jpg, .jpeg, .png"></img>
I think it is better to capitalize the sentence for a user:
`alt="user's avatar"`

2021-05-31 08:30 UTC, achehrynets commented on src/components/ProfilePage/Avatar/avatar.css
> +.img{
Fix code style:
`.img{`

2021-06-02 19:06 UTC, achehrynets requested changes
Requested changes.

2021-06-02 19:06 UTC, achehrynets commented on src/components/ProfilePage/Avatar/Avatar.js
> +    })
Fix code style issue.

2021-06-02 19:06 UTC, achehrynets commented on src/components/ProfilePage/Avatar/avatar.css
> +.avatar{
Fix code style issue.

2021-06-03 11:17 UTC, nelfan approved these changes
+1

2021-06-03 11:32 UTC, ChernykhVyacheslav approved these changes

2021-06-03 14:22 UTC, merged