Style and implementation of profile menu
nelfan/BORDA-React-UI pull request #9
Opened 2021-05-31 05:59 UTC by jules-n

Should be included to header.
Functionality:
 - opening profile page
 - redirect to boards page
 - logging out

2021-05-31 06:31 UTC, ChernykhVyacheslav approved these changes

2021-05-31 08:36 UTC, achehrynets requested changes
In general looks good, but please fix code style issues.

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/ProfileMenu.js
> +class ProfileMenu extends Component{
Fix code style:
`Component{`
One space should be between `Component` and `{`

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/ProfileMenu.js
> +    render (){
Fix code style:
One space should be between `)` and `{`

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/ProfileMenu.js
> +    const menu_window = () =>{
Fix code style:
One space should be between ) and {

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/ProfileMenu.js
> +    const clear_token = () =>{
Fix code style:
One space should be between ) and {

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/ProfileMenu.js
> +    const profile_window = () =>{
Fix code style:
One space should be between ) and {

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/profileMenu.css
> +.user_submenu{
Fix code style:
One space should be between `user_submenu` and `{`

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/profileMenu.css
> +.user_icon{
Fix code style

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/profileMenu.css
> +.user_submenu ul{
Fix code style:

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/profileMenu.css
> +.user_submenu ul li{
Fix code style:

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/profileMenu.css
> +.user_submenu ul li:hover{
Fix code style:

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/profileMenu.css
> +.user_submenu ul li i{
Fix code style

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/profileMenu.css
> +li a{
Fix code style

2021-05-31 08:36 UTC, achehrynets commented on src/components/Header/ProfileMenu/ProfileMenu.js
> +    )
Fix code formatting, it (`)`) cannot be on the same space level as the end of method block (`}`)

2021-06-02 19:04 UTC, achehrynets approved these changes
Looks good!

2021-06-03 11:02 UTC, merged